meta_product_name: "Eatamina"
meta_title: "Eatamina / Descifra lo que comes en un click"
meta_description: "Comer sano es la clave para tener calidad de vida. Ahora teneis a vuestra disposición un aplicación amiga, que os dira en un click, si lo que vas a comprar es tan sana como crees. "
meta_image: "logofav.png"                       # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"