meta_product_name: "Eatamina"
meta_title: "Eatamina / Descifra lo que comes en un click"
meta_description: "Eat well is a way to live better. Now you can improve your way of life using this fantastic feature that allows to you discover how bad each food are to your health and how it affects you."
meta_image: "logo.png"                       # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"